CREATE TABLE friends
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	friend_a VARCHAR(16) NOT NULL,
	friend_b VARCHAR(16) NOT NULL,
	confirmed TINYINT(1) DEFAULT 0,
	friendship_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (friend_a) REFERENCES users(username) ON DElETE CASCADE,
	FOREIGN KEY (friend_b) REFERENCES users(username) ON DELETE CASCADE
);
